stages:
  - build
  - publish

build:
  stage: build
  image: maven:3.6.3-jdk-11
  script:
    - mvn clean package -DskipTests
  only:
    - merge_requests
    - main
    - dev
    - ci
  artifacts:
    name: "backend"
    paths:
      - target/*.jar

publish:
  image: docker:dind
  stage: publish
  services:
    - docker:dind
  script:
    - if [ "$CI_COMMIT_BRANCH" == "main" ]; then TAG="latest"; else TAG="$CI_COMMIT_BRANCH"; fi
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH:${TAG} .
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH:${TAG}
  only:
    - dev
    - main
    - ci
  dependencies:
    - build
